### ISSUE TITLE
Browser compatibility?

### ISSUE THREAD

**Issue by elimisteve** [beyonk-adventures/svelte-notifications#11]
Would like to know, thanks!

**Comment by antony** [comment]
Are you using this standalone or as part of a Svelte (or other) app?

I personally use this and it works on IE11, Edge (Old), Edge (Chrome), Chrome, Firefox, and Safari.

However, I run the app that hosts it through a Babel config which supports this. In itself, if compiled to pure JavaScript, it would have the same support as Svelte itself - which is, Edge (Old), Edge (Chrome), Chrome, Firefox, Safari

So really depends on how you're using it.

**Comment by elimisteve** [comment]
I am using this with Svelte (3.20), yes.

**Comment by elimisteve** [comment]
Sounds like pretty great compatibility, thank you. Safari Mobile, too?

**Comment by antony** [comment]
Yep - it works well on Safari iOS :)
