### ISSUE TITLE
Option to close manually.

### ISSUE THREAD

**Issue by abhijitgujar86** [beyonk-adventures/svelte-notifications#19]
I liked this work. 
What i suggest is an manual close button for user. so this button when enabled will override the time. 
**use case** 

- This is important in case when we want user to know for sure. 
- sometimes if there is  long process then if the user is away from desk . this notification will help.

What do you think ?

we can implement it in below way 

notifier.success('Notifications work!',9999,True);

if True it will override the time and will show close icon.

**Comment by antony** [comment]
Fixed in v4 :)
