### ISSUE TITLE
Not working with Svelte 3

### ISSUE THREAD

**Issue by PaulMaly** [beyonk-adventures/svelte-notifications#2]
Hi! Thanks for this component. 

Can you help me to setup it for Svelte 3? I thought that the problem was in https://github.com/beyonk-adventures/svelte-notifications/pull/1 but it's not working too. In Devtools I see many items in `toasts` array but no one showing.

Any ideas?

**Comment by PaulMaly** [comment]
Actually, toasts start working with my patch, but after times up (on hiding) error occurs in the console:
`
internal.js:107 Uncaught (in promise) TypeError: Illegal invocation`

**Comment by PaulMaly** [comment]
@antony Any ideas?

**Comment by PaulMaly** [comment]
```
Uncaught (in promise) TypeError: Illegal invocation
    at loop (internal.js:107)
    at go (internal.js:676)
    at create_out_transition (internal.js:702)
    at Object.outro [as o] (Notifications.html:3)
    at outro_and_destroy_block (internal.js:886)
    at update_keyed_each (internal.js:962)
    at Object.update [as p] (Notifications.html:2)
    at update (internal.js:570)
    at flush (internal.js:545)
```

**Comment by antony** [comment]
Hi @PaulMaly - I'm surprised that this isn't working for you, as it appears to for me - and in fact I'm using i in a Svelte3 application.

however after studying #1 - I too can't figure out exactly *how*!

I'll review your PR and merge it, as well as try to fix this asap :)

**Comment by antony** [comment]
Hi @PaulMaly I believe this was due to an old svelte dependency which I have now removed.

It is now working properly in recent Svelte applications :)

Thanks for your help!
