### ISSUE TITLE
Timeout parameter for notifications shouldn't be required

### ISSUE THREAD

**Issue by mcmxcdev** [beyonk-adventures/svelte-notifications#29]
The types for `TNotifier` are e.g. `success(message: string, timeout: number): void`, which doesn't make sense since `timeout` has a defined default and user doesn't change it very often on a per-use basis IMO.

Also, most of the basic examples from the `README.md` don't even conform to these typings, and wouldn't pass TS compilation.

**Comment by antony** [comment]
Do you know how to fix these? I'm very green on TypeScript, so wouldn't really be able to address it myself.

**Comment by mhatvan** [comment]
I provided a PR for this ;)
